before:
  hooks:
    - go mod download
builds:
- main: ./cmd/kubectl-chonk.go
  binary: kubectl-chonk
  env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
- id: kubechonk-archive
  name_template: |-
      kubechonk-{{ .Tag }}-{{ .Os }}-{{ .Arch -}}
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
changelog:
  sort: asc
